#requires -Version 7.4
[CmdletBinding()]
param([switch]$AsJson)
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
function Run([string]$f,[string[]]$a,[string]$i=''){$s=[Diagnostics.ProcessStartInfo]::new($f);$s.UseShellExecute=$false;$s.RedirectStandardInput=$true;$s.RedirectStandardOutput=$true;$s.RedirectStandardError=$true;foreach($x in $a){[void]$s.ArgumentList.Add($x)};$p=[Diagnostics.Process]::new();$p.StartInfo=$s;[void]$p.Start();if($i.Length){$p.StandardInput.Write($i)};$p.StandardInput.Close();$o=$p.StandardOutput.ReadToEnd();$e=$p.StandardError.ReadToEnd();$p.WaitForExit();[pscustomobject]@{exit=$p.ExitCode;out=$o;err=$e}}
function Assert([bool]$c,[string]$m){if(-not $c){throw $m}}
function New-Repo([string]$r){New-Item -ItemType Directory $r|Out-Null;foreach($a in @(@('-C',$r,'init','-b','main'),@('-C',$r,'config','user.email','a@b.c'),@('-C',$r,'config','user.name','selftest'),@('-C',$r,'config','core.autocrlf','false'))){Assert ((Run git $a).exit -eq 0) 'git setup'};$u=[Text.UTF8Encoding]::new($false);[IO.File]::WriteAllText((Join-Path $r 'allowed.txt'),"one`n",$u);[IO.File]::WriteAllText((Join-Path $r 'other.txt'),"base`n",$u);Assert ((Run git @('-C',$r,'add','allowed.txt','other.txt')).exit -eq 0) 'git add';Assert ((Run git @('-C',$r,'commit','-m','base')).exit -eq 0) 'git commit'}
function Patch([string]$r,[string]$p='allowed.txt',[string]$n="two`n",[string]$o="one`n"){$u=[Text.UTF8Encoding]::new($false);[IO.File]::WriteAllText((Join-Path $r $p),$n,$u);$d=Run git @('-C',$r,'diff','--',$p);Assert ($d.exit -eq 0) 'git diff';[IO.File]::WriteAllText((Join-Path $r $p),$o,$u);$d.out}
function Dry([string]$r,[string[]]$allow,[string]$p){$a=@('-NoProfile','-File',$script:Engine,'-RepositoryRoot',$r);foreach($x in $allow){$a+=@('-AllowedPath',$x)};$a+='-DryRun';$z=Run pwsh $a ([Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($p)));[pscustomobject]@{n=$z;j=($z.out|ConvertFrom-Json)}}
function Apply([string]$r,[string[]]$allow,$j,[string]$hash){$a=@('-NoProfile','-File',$script:Engine,'-RepositoryRoot',$r);foreach($x in $allow){$a+=@('-AllowedPath',$x)};$z=Run pwsh ($a+@('-StagedPatchId',$j.stagedPatchId,'-ExpectedPatchSha256',$hash));[pscustomobject]@{n=$z;j=($z.out|ConvertFrom-Json)}}
function Code($x,[string]$want,[string]$name,[bool]$ok=$false){$detail=(($x.n.out+$x.n.err) -replace '\s+',' ').Trim();Assert ($x.j.code -eq $want) "$name got $($x.j.code): $detail";Assert (($x.n.exit -eq 0) -eq $ok) "$name exit"}
function Stage($id){Join-Path (Join-Path ([IO.Path]::GetTempPath()) 'GeneXus-XPZ-ApprovedPatch') $id}
$script:Engine=Join-Path $PSScriptRoot 'Apply-ApprovedPatch.ps1';$root=Join-Path ([IO.Path]::GetTempPath()) ('ApplyApprovedPatchSelfTest_'+[guid]::NewGuid().ToString('N'));$stages=[Collections.Generic.List[string]]::new();$tests=[Collections.Generic.List[object]]::new()
try{New-Item -ItemType Directory $root|Out-Null
$r=Join-Path $root 'happy';New-Repo $r;$d=Dry $r @('allowed.txt') (Patch $r);Code $d 'DRY_RUN_OK' 'dry' $true;[void]$stages.Add((Stage $d.j.stagedPatchId));Assert ([IO.File]::ReadAllText((Join-Path $r 'allowed.txt')) -eq "one`n") 'dry wrote';$a=Apply $r @('allowed.txt') $d.j $d.j.patchSha256;Code $a 'APPLIED' 'apply' $true;Assert ([IO.File]::ReadAllText((Join-Path $r 'allowed.txt')) -eq "two`n") 'apply bytes';$tests.Add('success')|Out-Null
$r=Join-Path $root 'path';New-Repo $r;Code (Dry $r @('allowed.txt') (Patch $r 'other.txt' "changed`n" "base`n")) 'PATH_NOT_ALLOWED' 'path';$tests.Add('path')|Out-Null
$r=Join-Path $root 'binary';New-Repo $r;Code (Dry $r @('allowed.txt') "diff --git a/allowed.txt b/allowed.txt`nGIT binary patch`nliteral 1`n") 'BINARY_PATCH_REJECTED' 'binary';$tests.Add('binary')|Out-Null
$r=Join-Path $root 'rename';New-Repo $r;Code (Dry $r @('allowed.txt') "diff --git a/allowed.txt b/renamed.txt`nsimilarity index 100%`nrename from allowed.txt`nrename to renamed.txt`n") 'RENAME_OR_COPY_REJECTED' 'rename';Code (Dry $r @('allowed.txt') "diff --git a/allowed.txt b/allowed.txt`nold mode 100644`nnew mode 100755`n") 'NON_TEXTUAL_MODE_REJECTED' 'mode';$tests.Add('rename-mode')|Out-Null
$r=Join-Path $root 'index';New-Repo $r;$p=Patch $r;[IO.File]::WriteAllText((Join-Path $r 'allowed.txt'),"staged`n",[Text.UTF8Encoding]::new($false));Assert ((Run git @('-C',$r,'add','allowed.txt')).exit -eq 0) 'stage';Code (Dry $r @('allowed.txt') $p) 'GIT_INDEX_HAS_STAGED_CHANGES' 'index';$tests.Add('index')|Out-Null
foreach($kind in @('hash','preimage','head','expiry')){$r=Join-Path $root $kind;New-Repo $r;$d=Dry $r @('allowed.txt') (Patch $r);Code $d 'DRY_RUN_OK' "$kind dry" $true;$s=Stage $d.j.stagedPatchId;[void]$stages.Add($s);if($kind -eq 'hash'){Code (Apply $r @('allowed.txt') $d.j ('0'*64)) 'PATCH_HASH_MISMATCH' 'hash'}elseif($kind -eq 'preimage'){[IO.File]::WriteAllText((Join-Path $r 'allowed.txt'),"drift`n",[Text.UTF8Encoding]::new($false));Code (Apply $r @('allowed.txt') $d.j $d.j.patchSha256) 'REPOSITORY_CONTEXT_CHANGED' 'preimage'}elseif($kind -eq 'head'){Assert ((Run git @('-C',$r,'commit','--allow-empty','-m','advance')).exit -eq 0) 'advance';Code (Apply $r @('allowed.txt') $d.j $d.j.patchSha256) 'REPOSITORY_CONTEXT_CHANGED' 'head'}else{$m=Get-Content (Join-Path $s 'manifest.json') -Raw|ConvertFrom-Json;$m.expiresUtc=[DateTime]::UtcNow.AddMinutes(-1).ToString('O');[IO.File]::WriteAllText((Join-Path $s 'manifest.json'),(($m|ConvertTo-Json -Compress -Depth 12)+"`n"),[Text.UTF8Encoding]::new($false));Code (Apply $r @('allowed.txt') $d.j $d.j.patchSha256) 'STAGED_PATCH_NOT_FOUND_OR_EXPIRED' 'expiry'};$tests.Add($kind)|Out-Null}
$r=Join-Path $root 'binding';New-Repo $r;$a=@('-NoProfile','-File',$script:Engine,'-RepositoryRoot',$r,'-AllowedPath','allowed.txt','-AllowedPath','other.txt','-DryRun');$raw=Run pwsh $a ([Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes((Patch $r))));Assert ($raw.exit -ne 0 -and (($raw.out+$raw.err) -match 'AllowedPath')) 'binding';$tests.Add('binding')|Out-Null
$r=Join-Path $root 'csv';New-Repo $r;Code (Dry $r @('allowed.txt,other.txt') (Patch $r)) 'PATH_NOT_ALLOWED' 'csv';$tests.Add('csv')|Out-Null
$r=Join-Path $root 'newline';New-Repo $r;$a=@('-NoProfile','-File',$script:Engine,'-RepositoryRoot',$r,'-AllowedPath','allowed.txt','-DryRun');$base64=[Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes((Patch $r)))+"`n";$raw=Run pwsh $a $base64;$newline=[pscustomobject]@{n=$raw;j=($raw.out|ConvertFrom-Json)};Code $newline 'INVALID_INPUT' 'newline';Assert ($newline.j.message -match 'Write' -and $newline.j.message -match 'Close' -and $newline.j.message -match 'newline') 'newline message';$tests.Add('newline')|Out-Null
$r=Join-Path $root 'crlf';New-Repo $r;$crlf=(Patch $r).Replace("`n","`r`n");Code (Dry $r @('allowed.txt') $crlf) 'MALFORMED_PATCH' 'crlf';$tests.Add('crlf')|Out-Null
$payload=[ordered]@{status='pass';code='SELFTEST_OK';token='APPLY_APPROVED_PATCH_SELFTEST_OK';tests=@($tests)};if($AsJson){[pscustomobject]$payload|ConvertTo-Json -Compress}else{$payload.token};exit 0
}catch{$payload=[ordered]@{status='fail';code='SELFTEST_FAILED';message=$_.Exception.Message;tests=@($tests)};if($AsJson){[pscustomobject]$payload|ConvertTo-Json -Compress}else{"SELFTEST_FAILED: $($_.Exception.Message)"};exit 1
}finally{foreach($s in $stages){if(Test-Path -LiteralPath $s){Remove-Item -LiteralPath $s -Recurse -Force}};if(Test-Path -LiteralPath $root){Remove-Item -LiteralPath $root -Recurse -Force}}
